[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.14",
    "aiohttp-cors>=0.8.1",
    "asyncpg>=0.30.0",
    "python-socketio>=5.13.0",
    "socketio>=0.2.1",
]
